global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "yu-rpc-provider"
    static_configs:
      - targets:
          - "yu-rpc-provider:9404"
  - job_name: "yu-rpc-client"
    static_configs:
      - targets:
          - "yu-rpc-client:9405"

