apiVersion: v1
kind: Service
metadata:
  name: yurpc-etcd
  namespace: yurpc
labels:
  app: yurpc-etcd
spec:
  ports:
    - name: client
      port: 2379
      targetPort: 2379
  clusterIP: None
  selector:
    app: yurpc-etcd
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: yurpc-etcd
  namespace: yurpc
  labels:
    app: yurpc-etcd
spec:
  serviceName: yurpc-etcd
  replicas: 1
  selector:
    matchLabels:
      app: yurpc-etcd
  template:
    metadata:
      labels:
        app: yurpc-etcd
    spec:
      containers:
        - name: etcd
          image: gcr.io/etcd-development/etcd:v3.5.15
          ports:
            - containerPort: 2379
              name: client
            - containerPort: 2380
              name: peer
          command:
            - /usr/local/bin/etcd
          args:
            - --name=yurpc-etcd
            - --data-dir=/var/lib/etcd
            - --advertise-client-urls=http://0.0.0.0:2379
            - --listen-client-urls=http://0.0.0.0:2379
            - --listen-peer-urls=http://0.0.0.0:2380
            - --initial-advertise-peer-urls=http://0.0.0.0:2380
            - --initial-cluster=yurpc-etcd=http://0.0.0.0:2380
            - --initial-cluster-state=new
          readinessProbe:
            httpGet:
              path: /health
              port: 2379
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - mountPath: /var/lib/etcd
              name: data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi


